spring.application.name=DataShare

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:datashare}
spring.datasource.username=${POSTGRES_USER:datashare}
spring.datasource.password=${POSTGRES_PASSWORD:datashare_dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000

storage.upload-dir=../uploads

spring.servlet.multipart.max-file-size=1100MB
spring.servlet.multipart.max-request-size=1100MB
